apiVersion: apps/v1
kind: Deployment
metadata:
  name: <PROJECT_NAME>
  namespace: <NAMESPACE>
  labels:
    app: <PROJECT_NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <PROJECT_NAME>
  template:
    metadata:
      labels:
        app: <PROJECT_NAME>
    spec:
      containers:
        - name: <PROJECT_NAME>
          image: <REGISTRY>/<DOCKERHUB_NAMESPACE>/<PROJECT_NAME>:SNAPSHOT-<BUILD_NUMBER>
          ports:
            - name: http-h5
              containerPort: 80
      imagePullSecrets:
        - name: <HARBOR_SECRET>
