spring:
    datasource:
        url: jdbc:mysql://121.36.67.81:3306/meeting-appointment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    data:
        redis:
            host: 1.94.57.107
            port: 6379
            password: meetingredis
            database: 0
