spring:
    datasource:
        url: jdbc:mysql://172.17.34.51:32306/meeting-appointment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: meeting-appointment
        password: 8tnKF8m%Ee
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    data:
        redis:
            host: 1.94.57.107
            port: 6379
            password: meetingredis
            database: 0





