server:
  #  port: 8080
  port: 8080

spring:
  application:
    name: meeting-appointment
  profiles:
    active: prod
    include: db,log,common,modules,quartz
  # application.yml
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  #    time-zone: Asia/Shanghai
  #    包含时区信息

  #允许循环依赖
  main:
    allow-circular-references: true

mybatis-plus:
  configuration:
    cache-enabled: true
    # 配置下划线转驼峰
    map-underscore-to-camel-case: true
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #     logic-delete-field: is_deleted 逻辑删除，需要的在实体类具体字段加@TableLogic
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.jfzt.meeting: debug
sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: jfzt
    user-ttl: 7200000000000

    user-token-name: authorization

# 企业微信配置
#qiyewx:
#  corpid: ww942086e6c44abc4b
#  corpsecret: Rnf3LVxbAdTfvGVTirgwVbgsaDoBv_MTXrmawAu9qHQ
#  agentId: 1000002
#  url: http://llzzxx.cn
#  state: WWLogin
#  #回调配置
#  token: 9zTIV
#  encodingAESKey: fha6hIaBwGCkU3R4IgV2SRHOCYd5EmVVVrKq71HqSQX
#
#  scope: snsapi_base
# 企业微信配置
qiyewx:
  corpid: wwfa655ac032fa1cff
  corpsecret: uZongcdBQh3eOrsos2x910dVA2gMtE4KFG7KP0ewfUc
  agentId: 1000021
  url: http://192.168.212.41:31505
  #回调配置
  token: 9zTIV
  encodingAESKey: fha6hIaBwGCkU3R4IgV2SRHOCYd5EmVVVrKq71HqSQX
  state: WWLogin
  scope: snsapi_base