spring:
    datasource:
        url: jdbc:mysql://192.168.212.41:32306/meeting-appointment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: meeting-appointment
        password: OOLd8P7zK
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    data:
        redis:
            host: 1.94.57.107
            port: 6379
            password: meetingredis
            database: 0
sky:
    jwt:
        # 设置jwt签名加密时使用的秘钥
        admin-secret-key: itcast
        # 设置jwt过期时间
        admin-ttl: 7200000000000
        # 设置前端传递过来的令牌名称
        admin-token-name: token
        user-secret-key: jfzt
        user-ttl: 7200000000000

        user-token-name: authorization