spring:
    datasource:
        url: jdbc:mysql://192.168.212.41:32306/meeting-appointment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: meeting-appointment
        password: OOLd8P7zK
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    data:
        redis:
            host: 1.94.57.107
            port: 6379
            password: meetingredis
            database: 0
