spring:
  datasource:
    url: jdbc:mysql://1.94.57.107:3306/meeting_appointment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  data:
#    redis:
#      host: 1.94.57.107
#      port: 6379
#      database: 0
mybatis-plus:
  configuration:
    cache-enabled: true
    # 配置下划线转驼峰
    map-underscore-to-camel-case: true
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


qywx:
  corpid: ww942086e6c44abc4b
  corpsecret: Rnf3LVxbAdTfvGVTirgwVbgsaDoBv_MTXrmawAu9qHQ
  agentid: 1000002






